# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-prompt", "~> 0.23.1"

gem "colorize", "~> 1.1"

gem "lolize", "~> 0.0.3"

gem "rspec", "~> 3.12"
